version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 6.15.1
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.1.0
    - 7.2.1
    - 7.2.3
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
    - 2.21.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
  - dependency-name: "@stripe/stripe-js"
    versions:
    - 1.12.1
    - 1.13.0
    - 1.13.1
  - dependency-name: mapbox-gl
    versions:
    - 1.13.1
    - 2.1.1
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: web-vitals
    versions:
    - 1.1.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
